name: LaTeX-Build

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: pLMT-Mitschriften_2025.tex

      - name: Prepare PDF for Pages
        run: |
          mkdir -p public
          cp pLMT-Mitschriften_2025.pdf public/pLMT_VL-Mitschrift_2025.pdf
          cp index.html public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public