name: LaTeX-Build

on: [push]

permissions:
  contents: write # Wichtig für GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: pLMT-Mitschriften_2025.tex 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_file: pLMT VL-Mitschrift 2025.pdf # Die Datei, die du veröffentlichen willst